/*
 * This file is generated by jOOQ.
 */
package ge.tsu.weather.classes;


import ge.tsu.weather.classes.tables.FlywaySchemaHistory;
import ge.tsu.weather.classes.tables.Weather;
import ge.tsu.weather.classes.tables.records.FlywaySchemaHistoryRecord;
import ge.tsu.weather.classes.tables.records.WeatherRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<WeatherRecord> STATUS_PK = Internal.createUniqueKey(Weather.WEATHER, DSL.name("status_pk"), new TableField[] { Weather.WEATHER.ID }, true);
}
