/*
 * This file is generated by jOOQ.
 */
package ge.tsu.weather.classes;


import ge.tsu.weather.classes.tables.FlywaySchemaHistory;
import ge.tsu.weather.classes.tables.Weather;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.weather</code>.
     */
    public static final Weather WEATHER = Weather.WEATHER;
}
